/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e0e3e5",
        "secondary-fixed-dim": "#b9c7df",
        "on-primary-fixed": "#131b2e",
        "surface-dim": "#d8dadc",
        "tertiary-fixed-dim": "#4ae176",
        "on-tertiary-fixed-variant": "#005321",
        "inverse-surface": "#2d3133",
        "secondary-container": "#d5e3fc",
        "on-tertiary-fixed": "#002109",
        "on-surface-variant": "#45464d",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-container": "#131b2e",
        "on-secondary-container": "#57657a",
        "primary-fixed-dim": "#bec6e0",
        "outline-variant": "#c6c6cd",
        "on-surface": "#191c1e",
        background: "#f7f9fb",
        "on-tertiary-container": "#009844",
        "tertiary-fixed": "#6bff8f",
        "surface-container": "#eceef0",
        "on-primary-fixed-variant": "#3f465c",
        "on-primary-container": "#7c839b",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f7f9fb",
        "tertiary-container": "#002109",
        "on-background": "#191c1e",
        primary: "#000000",
        "on-secondary-fixed-variant": "#3a485b",
        "inverse-on-surface": "#eff1f3",
        "error-container": "#ffdad6",
        surface: "#f7f9fb",
        "surface-container-highest": "#e0e3e5",
        "on-error-container": "#93000a",
        "surface-container-high": "#e6e8ea",
        "inverse-primary": "#bec6e0",
        error: "#ba1a1a",
        outline: "#76777d",
        "secondary-fixed": "#d5e3fc",
        "surface-tint": "#565e74",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#0d1c2e",
        secondary: "#515f74",
        "primary-fixed": "#dae2fd",
        "surface-container-low": "#f2f4f6",
        tertiary: "#000000",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
